.timer on

DROP TABLE IF EXISTS Feed;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS FeedConfig;
DROP TABLE IF EXISTS Repository;
DROP TABLE IF EXISTS RevisionInfo;
DROP TABLE IF EXISTS LinkType;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS ItemHistory;
DROP TABLE IF EXISTS MetaData;
DROP TABLE IF EXISTS MetaDataHistory;
DROP TABLE IF EXISTS Task;
DROP TABLE IF EXISTS RunSession;

VACUUM;

